[shell] Fix powerful cd, namely the substitution functionality

diff --git a/sh/shellrc b/sh/shellrc
--- a/sh/shellrc
+++ b/sh/shellrc
@@ -97,21 +97,20 @@ fi
 
 # Powerful cd
 _cd_sub() {
+	set -- "$@" "$1"
 	while :; do
-		case "$1" in
-		*/"$3"/*)
-			set -- "${1%/"$3"/*}" "${1##*/"$3"/}$2" "$3" "$4"
-			if [ -d "$1/$4/$2" ]; then
-				echo "$1/$4/$2"
-				\cd "$1/$4/$2"
-				return $?
-			fi
-			set -- "$1/" "$3/$2" "$1" "$2"
-			;;
-		*)
-			echo "cd: $3 not found in $1$2 or resulting path does not point to a directory" >&2
+		if [ x"$4" = x"${4#*/"$2"/}" ]; then
+			echo "cd: $2 not found in $1 or resulting path does not point to a directory" >&2
 			return 1
-		esac
+		fi
+
+		set -- "$1" "$2" "$3" "${4%/"$2"/*}" "${4##*/"$2"/}/$5"
+		if [ -d "$4/$3/$5" ]; then
+			\cd "$4/$3/$5"
+			return $?
+		fi
+
+		set -- "$1" "$2" "$3" "$4" "$2/$5"
 	done
 }
 
